(cl:in-package lcr_shared-msg)
(cl:export '(VIRTUAL_OBJECT_VERSION_ID-VAL
          VIRTUAL_OBJECT_VERSION_ID
          MISSION_ID-VAL
          MISSION_ID
          WCS_ADAPTER_ROS_HEADER-VAL
          WCS_ADAPTER_ROS_HEADER
          STATUS-VAL
          STATUS
          TAG_SEEN-VAL
          TAG_SEEN
          POSITION-VAL
          POSITION
          YAW-VAL
          YAW
          NAVIGATION_HEADER-VAL
          NAVIGATION_HEADER
          ERROR_TYPE-VAL
          ERROR_TYPE
          ERROR_ID-VAL
          ERROR_ID
          ERROR_HEADER-VAL
          ERROR_HEADER
          EMERGENZA-VAL
          EMERGENZA
          BUMP_FRONT-VAL
          BUMP_FRONT
          BUMP_REAR-VAL
          BUMP_REAR
          FALL_FRONT-VAL
          FALL_FRONT
          FALL_REAR-VAL
          FALL_REAR
          MOTORE_DX_FAIL-VAL
          MOTORE_DX_FAIL
          MOTORE_SX_FAIL-VAL
          MOTORE_SX_FAIL
          ERRORE_INT_1-VAL
          ERRORE_INT_1
          ERRORE_INT_2-VAL
          ERRORE_INT_2
          BATTERY_FAIL-VAL
          BATTERY_FAIL
          BATTERY_POWER-VAL
          BATTERY_POWER
          RECHARGE_FOUND-VAL
          RECHARGE_FOUND
          RECHARGE_ON-VAL
          RECHARGE_ON
          RECHARGE_OK-VAL
          RECHARGE_OK
          HARDWARE_STATUS_HEADER-VAL
          HARDWARE_STATUS_HEADER
          SERIAL_OK-VAL
          SERIAL_OK
          SERIAL_INFO-VAL
          SERIAL_INFO
          SERIAL_HEADER-VAL
          SERIAL_HEADER
          LASER_OK-VAL
          LASER_OK
          LASER_INFO-VAL
          LASER_INFO
          LASER_HEADER-VAL
          LASER_HEADER
          PLANNER_STATUS-VAL
          PLANNER_STATUS
          PLANNER_INFO-VAL
          PLANNER_INFO
          CONTROLLER_STATUS-VAL
          CONTROLLER_STATUS
          NEXTNODE-VAL
          NEXTNODE
))