(cl:defpackage lcr_shared-msg
  (:use )
  (:export
   "<ELEVATORSTATUS>"
   "ELEVATORSTATUS"
   "<LCRERROR>"
   "LCRERROR"
   "<LCRSTATUS>"
   "LCRSTATUS"
   "<LCRTAGSAVER>"
   "LCRTAGSAVER"
   "<VIRTUALOBJECTSANDPATHS>"
   "VIRTUALOBJECTSANDPATHS"
   "<WCS_STATUS>"
   "WCS_STATUS"
  ))

