; Auto-generated. Do not edit!


(cl:in-package lcr_shared-msg)


;//! \htmlinclude VirtualObjectsAndPaths.msg.html

(cl:defclass <VirtualObjectsAndPaths> (roslisp-msg-protocol:ros-message)
  ((version
    :reader version
    :initarg :version
    :type cl:integer
    :initform 0)
   (virtualObjects_Id
    :reader virtualObjects_Id
    :initarg :virtualObjects_Id
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (virtualObjects_Name
    :reader virtualObjects_Name
    :initarg :virtualObjects_Name
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element ""))
   (virtualObjects_ObjectType
    :reader virtualObjects_ObjectType
    :initarg :virtualObjects_ObjectType
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (virtualObjects_PositionX
    :reader virtualObjects_PositionX
    :initarg :virtualObjects_PositionX
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (virtualObjects_PositionY
    :reader virtualObjects_PositionY
    :initarg :virtualObjects_PositionY
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (virtualObjects_Rotation
    :reader virtualObjects_Rotation
    :initarg :virtualObjects_Rotation
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (virtualObjects_ShapeType
    :reader virtualObjects_ShapeType
    :initarg :virtualObjects_ShapeType
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (paths_Id
    :reader paths_Id
    :initarg :paths_Id
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (paths_CurvePointX
    :reader paths_CurvePointX
    :initarg :paths_CurvePointX
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (paths_CurvePointY
    :reader paths_CurvePointY
    :initarg :paths_CurvePointY
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (paths_Direction
    :reader paths_Direction
    :initarg :paths_Direction
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (paths_EndPoint
    :reader paths_EndPoint
    :initarg :paths_EndPoint
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (paths_Name
    :reader paths_Name
    :initarg :paths_Name
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element ""))
   (paths_PathType
    :reader paths_PathType
    :initarg :paths_PathType
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (paths_StartPoint
    :reader paths_StartPoint
    :initarg :paths_StartPoint
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass VirtualObjectsAndPaths (<VirtualObjectsAndPaths>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <VirtualObjectsAndPaths>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'VirtualObjectsAndPaths)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lcr_shared-msg:<VirtualObjectsAndPaths> is deprecated: use lcr_shared-msg:VirtualObjectsAndPaths instead.")))

(cl:ensure-generic-function 'version-val :lambda-list '(m))
(cl:defmethod version-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:version-val is deprecated.  Use lcr_shared-msg:version instead.")
  (version m))

(cl:ensure-generic-function 'virtualObjects_Id-val :lambda-list '(m))
(cl:defmethod virtualObjects_Id-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:virtualObjects_Id-val is deprecated.  Use lcr_shared-msg:virtualObjects_Id instead.")
  (virtualObjects_Id m))

(cl:ensure-generic-function 'virtualObjects_Name-val :lambda-list '(m))
(cl:defmethod virtualObjects_Name-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:virtualObjects_Name-val is deprecated.  Use lcr_shared-msg:virtualObjects_Name instead.")
  (virtualObjects_Name m))

(cl:ensure-generic-function 'virtualObjects_ObjectType-val :lambda-list '(m))
(cl:defmethod virtualObjects_ObjectType-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:virtualObjects_ObjectType-val is deprecated.  Use lcr_shared-msg:virtualObjects_ObjectType instead.")
  (virtualObjects_ObjectType m))

(cl:ensure-generic-function 'virtualObjects_PositionX-val :lambda-list '(m))
(cl:defmethod virtualObjects_PositionX-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:virtualObjects_PositionX-val is deprecated.  Use lcr_shared-msg:virtualObjects_PositionX instead.")
  (virtualObjects_PositionX m))

(cl:ensure-generic-function 'virtualObjects_PositionY-val :lambda-list '(m))
(cl:defmethod virtualObjects_PositionY-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:virtualObjects_PositionY-val is deprecated.  Use lcr_shared-msg:virtualObjects_PositionY instead.")
  (virtualObjects_PositionY m))

(cl:ensure-generic-function 'virtualObjects_Rotation-val :lambda-list '(m))
(cl:defmethod virtualObjects_Rotation-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:virtualObjects_Rotation-val is deprecated.  Use lcr_shared-msg:virtualObjects_Rotation instead.")
  (virtualObjects_Rotation m))

(cl:ensure-generic-function 'virtualObjects_ShapeType-val :lambda-list '(m))
(cl:defmethod virtualObjects_ShapeType-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:virtualObjects_ShapeType-val is deprecated.  Use lcr_shared-msg:virtualObjects_ShapeType instead.")
  (virtualObjects_ShapeType m))

(cl:ensure-generic-function 'paths_Id-val :lambda-list '(m))
(cl:defmethod paths_Id-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:paths_Id-val is deprecated.  Use lcr_shared-msg:paths_Id instead.")
  (paths_Id m))

(cl:ensure-generic-function 'paths_CurvePointX-val :lambda-list '(m))
(cl:defmethod paths_CurvePointX-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:paths_CurvePointX-val is deprecated.  Use lcr_shared-msg:paths_CurvePointX instead.")
  (paths_CurvePointX m))

(cl:ensure-generic-function 'paths_CurvePointY-val :lambda-list '(m))
(cl:defmethod paths_CurvePointY-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:paths_CurvePointY-val is deprecated.  Use lcr_shared-msg:paths_CurvePointY instead.")
  (paths_CurvePointY m))

(cl:ensure-generic-function 'paths_Direction-val :lambda-list '(m))
(cl:defmethod paths_Direction-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:paths_Direction-val is deprecated.  Use lcr_shared-msg:paths_Direction instead.")
  (paths_Direction m))

(cl:ensure-generic-function 'paths_EndPoint-val :lambda-list '(m))
(cl:defmethod paths_EndPoint-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:paths_EndPoint-val is deprecated.  Use lcr_shared-msg:paths_EndPoint instead.")
  (paths_EndPoint m))

(cl:ensure-generic-function 'paths_Name-val :lambda-list '(m))
(cl:defmethod paths_Name-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:paths_Name-val is deprecated.  Use lcr_shared-msg:paths_Name instead.")
  (paths_Name m))

(cl:ensure-generic-function 'paths_PathType-val :lambda-list '(m))
(cl:defmethod paths_PathType-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:paths_PathType-val is deprecated.  Use lcr_shared-msg:paths_PathType instead.")
  (paths_PathType m))

(cl:ensure-generic-function 'paths_StartPoint-val :lambda-list '(m))
(cl:defmethod paths_StartPoint-val ((m <VirtualObjectsAndPaths>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lcr_shared-msg:paths_StartPoint-val is deprecated.  Use lcr_shared-msg:paths_StartPoint instead.")
  (paths_StartPoint m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<VirtualObjectsAndPaths>)))
    "Constants for message type '<VirtualObjectsAndPaths>"
  '((:OBJECTTYPE_TAG . -3)
    (:OBJECTTYPE_RECHARGE_WAYPOINT . -2)
    (:OBJECTTYPE_NONE . -1)
    (:OBJECTTYPE_OBSTACLE . 0)
    (:OBJECTTYPE_CHARGEPOINT . 1)
    (:OBJECTTYPE_CHECKPOINT . 2)
    (:OBJECTTYPE_SPEED_LIMIT_ZONE . 3)
    (:OBJECTTYPE_NO_DISTANCE_ZONE . 4)
    (:SHAPETYPE_NONE . -1)
    (:SHAPETYPE_LINE . 0)
    (:SHAPETYPE_RECTANGLE . 1)
    (:SHAPETYPE_CIRCLE . 2)
    (:SHAPETYPE_POLYGON . 3)
    (:PATHTYPE_LINEPATH . 0)
    (:PATHTYPE_CURVEPATH . 1)
    (:PATHDIRECTION_TWO_WAY . 0)
    (:PATHDIRECTION_FROM_A_TO_B . 1)
    (:PATHDIRECTION_FROM_B_TO_A . 2)
    (:PATHDIRECTION_ALTERNATING_ONE_WAY . 3))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'VirtualObjectsAndPaths)))
    "Constants for message type 'VirtualObjectsAndPaths"
  '((:OBJECTTYPE_TAG . -3)
    (:OBJECTTYPE_RECHARGE_WAYPOINT . -2)
    (:OBJECTTYPE_NONE . -1)
    (:OBJECTTYPE_OBSTACLE . 0)
    (:OBJECTTYPE_CHARGEPOINT . 1)
    (:OBJECTTYPE_CHECKPOINT . 2)
    (:OBJECTTYPE_SPEED_LIMIT_ZONE . 3)
    (:OBJECTTYPE_NO_DISTANCE_ZONE . 4)
    (:SHAPETYPE_NONE . -1)
    (:SHAPETYPE_LINE . 0)
    (:SHAPETYPE_RECTANGLE . 1)
    (:SHAPETYPE_CIRCLE . 2)
    (:SHAPETYPE_POLYGON . 3)
    (:PATHTYPE_LINEPATH . 0)
    (:PATHTYPE_CURVEPATH . 1)
    (:PATHDIRECTION_TWO_WAY . 0)
    (:PATHDIRECTION_FROM_A_TO_B . 1)
    (:PATHDIRECTION_FROM_B_TO_A . 2)
    (:PATHDIRECTION_ALTERNATING_ONE_WAY . 3))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <VirtualObjectsAndPaths>) ostream)
  "Serializes a message object of type '<VirtualObjectsAndPaths>"
  (cl:let* ((signed (cl:slot-value msg 'version)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'virtualObjects_Id))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'virtualObjects_Id))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'virtualObjects_Name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'virtualObjects_Name))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'virtualObjects_ObjectType))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    ))
   (cl:slot-value msg 'virtualObjects_ObjectType))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'virtualObjects_PositionX))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'virtualObjects_PositionX))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'virtualObjects_PositionY))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'virtualObjects_PositionY))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'virtualObjects_Rotation))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'virtualObjects_Rotation))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'virtualObjects_ShapeType))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    ))
   (cl:slot-value msg 'virtualObjects_ShapeType))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'paths_Id))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'paths_Id))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'paths_CurvePointX))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'paths_CurvePointX))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'paths_CurvePointY))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'paths_CurvePointY))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'paths_Direction))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'paths_Direction))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'paths_EndPoint))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'paths_EndPoint))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'paths_Name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'paths_Name))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'paths_PathType))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    ))
   (cl:slot-value msg 'paths_PathType))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'paths_StartPoint))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'paths_StartPoint))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <VirtualObjectsAndPaths>) istream)
  "Deserializes a message object of type '<VirtualObjectsAndPaths>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'version) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'virtualObjects_Id) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'virtualObjects_Id)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'virtualObjects_Name) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'virtualObjects_Name)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'virtualObjects_ObjectType) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'virtualObjects_ObjectType)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'virtualObjects_PositionX) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'virtualObjects_PositionX)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'virtualObjects_PositionY) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'virtualObjects_PositionY)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'virtualObjects_Rotation) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'virtualObjects_Rotation)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'virtualObjects_ShapeType) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'virtualObjects_ShapeType)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'paths_Id) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'paths_Id)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'paths_CurvePointX) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'paths_CurvePointX)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'paths_CurvePointY) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'paths_CurvePointY)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'paths_Direction) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'paths_Direction)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'paths_EndPoint) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'paths_EndPoint)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'paths_Name) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'paths_Name)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'paths_PathType) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'paths_PathType)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'paths_StartPoint) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'paths_StartPoint)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<VirtualObjectsAndPaths>)))
  "Returns string type for a message object of type '<VirtualObjectsAndPaths>"
  "lcr_shared/VirtualObjectsAndPaths")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'VirtualObjectsAndPaths)))
  "Returns string type for a message object of type 'VirtualObjectsAndPaths"
  "lcr_shared/VirtualObjectsAndPaths")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<VirtualObjectsAndPaths>)))
  "Returns md5sum for a message object of type '<VirtualObjectsAndPaths>"
  "20a0913958c29e6abb9bdb538fd57fdd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'VirtualObjectsAndPaths)))
  "Returns md5sum for a message object of type 'VirtualObjectsAndPaths"
  "20a0913958c29e6abb9bdb538fd57fdd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<VirtualObjectsAndPaths>)))
  "Returns full string definition for message of type '<VirtualObjectsAndPaths>"
  (cl:format cl:nil "int32 version~%~%int8 OBJECTTYPE_TAG = -3~%int8 OBJECTTYPE_RECHARGE_WAYPOINT = -2~%int8 OBJECTTYPE_NONE = -1~%int8 OBJECTTYPE_OBSTACLE = 0~%int8 OBJECTTYPE_CHARGEPOINT = 1~%int8 OBJECTTYPE_CHECKPOINT = 2~%int8 OBJECTTYPE_SPEED_LIMIT_ZONE = 3~%int8 OBJECTTYPE_NO_DISTANCE_ZONE = 4~%~%int8 SHAPETYPE_NONE = -1~%int8 SHAPETYPE_LINE = 0~%int8 SHAPETYPE_RECTANGLE = 1~%int8 SHAPETYPE_CIRCLE = 2~%int8 SHAPETYPE_POLYGON = 3~%~%int32[] virtualObjects_Id~%string[] virtualObjects_Name~%int8[] virtualObjects_ObjectType~%int32[] virtualObjects_PositionX~%int32[] virtualObjects_PositionY~%float64[] virtualObjects_Rotation~%int8[] virtualObjects_ShapeType~%~%int8 PATHTYPE_LINEPATH = 0~%int8 PATHTYPE_CURVEPATH = 1~%~%int8 PATHDIRECTION_TWO_WAY = 0~%int8 PATHDIRECTION_FROM_A_TO_B = 1~%int8 PATHDIRECTION_FROM_B_TO_A = 2~%int8 PATHDIRECTION_ALTERNATING_ONE_WAY = 3~%~%int32[] paths_Id~%int32[] paths_CurvePointX~%int32[] paths_CurvePointY~%int32[] paths_Direction~%int32[] paths_EndPoint~%string[] paths_Name~%int8[] paths_PathType~%int32[] paths_StartPoint~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'VirtualObjectsAndPaths)))
  "Returns full string definition for message of type 'VirtualObjectsAndPaths"
  (cl:format cl:nil "int32 version~%~%int8 OBJECTTYPE_TAG = -3~%int8 OBJECTTYPE_RECHARGE_WAYPOINT = -2~%int8 OBJECTTYPE_NONE = -1~%int8 OBJECTTYPE_OBSTACLE = 0~%int8 OBJECTTYPE_CHARGEPOINT = 1~%int8 OBJECTTYPE_CHECKPOINT = 2~%int8 OBJECTTYPE_SPEED_LIMIT_ZONE = 3~%int8 OBJECTTYPE_NO_DISTANCE_ZONE = 4~%~%int8 SHAPETYPE_NONE = -1~%int8 SHAPETYPE_LINE = 0~%int8 SHAPETYPE_RECTANGLE = 1~%int8 SHAPETYPE_CIRCLE = 2~%int8 SHAPETYPE_POLYGON = 3~%~%int32[] virtualObjects_Id~%string[] virtualObjects_Name~%int8[] virtualObjects_ObjectType~%int32[] virtualObjects_PositionX~%int32[] virtualObjects_PositionY~%float64[] virtualObjects_Rotation~%int8[] virtualObjects_ShapeType~%~%int8 PATHTYPE_LINEPATH = 0~%int8 PATHTYPE_CURVEPATH = 1~%~%int8 PATHDIRECTION_TWO_WAY = 0~%int8 PATHDIRECTION_FROM_A_TO_B = 1~%int8 PATHDIRECTION_FROM_B_TO_A = 2~%int8 PATHDIRECTION_ALTERNATING_ONE_WAY = 3~%~%int32[] paths_Id~%int32[] paths_CurvePointX~%int32[] paths_CurvePointY~%int32[] paths_Direction~%int32[] paths_EndPoint~%string[] paths_Name~%int8[] paths_PathType~%int32[] paths_StartPoint~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <VirtualObjectsAndPaths>))
  (cl:+ 0
     4
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'virtualObjects_Id) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'virtualObjects_Name) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'virtualObjects_ObjectType) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'virtualObjects_PositionX) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'virtualObjects_PositionY) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'virtualObjects_Rotation) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'virtualObjects_ShapeType) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'paths_Id) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'paths_CurvePointX) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'paths_CurvePointY) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'paths_Direction) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'paths_EndPoint) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'paths_Name) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'paths_PathType) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'paths_StartPoint) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <VirtualObjectsAndPaths>))
  "Converts a ROS message object to a list"
  (cl:list 'VirtualObjectsAndPaths
    (cl:cons ':version (version msg))
    (cl:cons ':virtualObjects_Id (virtualObjects_Id msg))
    (cl:cons ':virtualObjects_Name (virtualObjects_Name msg))
    (cl:cons ':virtualObjects_ObjectType (virtualObjects_ObjectType msg))
    (cl:cons ':virtualObjects_PositionX (virtualObjects_PositionX msg))
    (cl:cons ':virtualObjects_PositionY (virtualObjects_PositionY msg))
    (cl:cons ':virtualObjects_Rotation (virtualObjects_Rotation msg))
    (cl:cons ':virtualObjects_ShapeType (virtualObjects_ShapeType msg))
    (cl:cons ':paths_Id (paths_Id msg))
    (cl:cons ':paths_CurvePointX (paths_CurvePointX msg))
    (cl:cons ':paths_CurvePointY (paths_CurvePointY msg))
    (cl:cons ':paths_Direction (paths_Direction msg))
    (cl:cons ':paths_EndPoint (paths_EndPoint msg))
    (cl:cons ':paths_Name (paths_Name msg))
    (cl:cons ':paths_PathType (paths_PathType msg))
    (cl:cons ':paths_StartPoint (paths_StartPoint msg))
))
