# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mars_agent_physical_robot_msgs/Position.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mars_common_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class Position(genpy.Message):
  _md5sum = "fb12308ac46fc4f6ee1916cd18375ae9"
  _type = "mars_agent_physical_robot_msgs/Position"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """mars_common_msgs/Id robot_id
geometry_msgs/PoseStamped current_position
geometry_msgs/Twist current_velocity

================================================================================
MSG: mars_common_msgs/Id
# Universally Unique Identifier (UUID)
# A UUID is a 128-bit number used to identify information in computer systems. 
# The term globally unique identifier (GUID) is also used. 
# More information: https://en.wikipedia.org/wiki/Universally_unique_identifier
uint8[16] uuid

# optional description of the id
# description can be:
#   - a name
#   - what is descriped by the id
#   - etc.
string description

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['robot_id','current_position','current_velocity']
  _slot_types = ['mars_common_msgs/Id','geometry_msgs/PoseStamped','geometry_msgs/Twist']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robot_id,current_position,current_velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Position, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.robot_id is None:
        self.robot_id = mars_common_msgs.msg.Id()
      if self.current_position is None:
        self.current_position = geometry_msgs.msg.PoseStamped()
      if self.current_velocity is None:
        self.current_velocity = geometry_msgs.msg.Twist()
    else:
      self.robot_id = mars_common_msgs.msg.Id()
      self.current_position = geometry_msgs.msg.PoseStamped()
      self.current_velocity = geometry_msgs.msg.Twist()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.robot_id.uuid
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_16B().pack(*_x))
      else:
        buff.write(_get_struct_16s().pack(_x))
      _x = self.robot_id.description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.current_position.header.seq, _x.current_position.header.stamp.secs, _x.current_position.header.stamp.nsecs))
      _x = self.current_position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_13d().pack(_x.current_position.pose.position.x, _x.current_position.pose.position.y, _x.current_position.pose.position.z, _x.current_position.pose.orientation.x, _x.current_position.pose.orientation.y, _x.current_position.pose.orientation.z, _x.current_position.pose.orientation.w, _x.current_velocity.linear.x, _x.current_velocity.linear.y, _x.current_velocity.linear.z, _x.current_velocity.angular.x, _x.current_velocity.angular.y, _x.current_velocity.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.robot_id is None:
        self.robot_id = mars_common_msgs.msg.Id()
      if self.current_position is None:
        self.current_position = geometry_msgs.msg.PoseStamped()
      if self.current_velocity is None:
        self.current_velocity = geometry_msgs.msg.Twist()
      end = 0
      start = end
      end += 16
      self.robot_id.uuid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robot_id.description = str[start:end].decode('utf-8')
      else:
        self.robot_id.description = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.current_position.header.seq, _x.current_position.header.stamp.secs, _x.current_position.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.current_position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.current_position.pose.position.x, _x.current_position.pose.position.y, _x.current_position.pose.position.z, _x.current_position.pose.orientation.x, _x.current_position.pose.orientation.y, _x.current_position.pose.orientation.z, _x.current_position.pose.orientation.w, _x.current_velocity.linear.x, _x.current_velocity.linear.y, _x.current_velocity.linear.z, _x.current_velocity.angular.x, _x.current_velocity.angular.y, _x.current_velocity.angular.z,) = _get_struct_13d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.robot_id.uuid
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_16B().pack(*_x))
      else:
        buff.write(_get_struct_16s().pack(_x))
      _x = self.robot_id.description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.current_position.header.seq, _x.current_position.header.stamp.secs, _x.current_position.header.stamp.nsecs))
      _x = self.current_position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_13d().pack(_x.current_position.pose.position.x, _x.current_position.pose.position.y, _x.current_position.pose.position.z, _x.current_position.pose.orientation.x, _x.current_position.pose.orientation.y, _x.current_position.pose.orientation.z, _x.current_position.pose.orientation.w, _x.current_velocity.linear.x, _x.current_velocity.linear.y, _x.current_velocity.linear.z, _x.current_velocity.angular.x, _x.current_velocity.angular.y, _x.current_velocity.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.robot_id is None:
        self.robot_id = mars_common_msgs.msg.Id()
      if self.current_position is None:
        self.current_position = geometry_msgs.msg.PoseStamped()
      if self.current_velocity is None:
        self.current_velocity = geometry_msgs.msg.Twist()
      end = 0
      start = end
      end += 16
      self.robot_id.uuid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robot_id.description = str[start:end].decode('utf-8')
      else:
        self.robot_id.description = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.current_position.header.seq, _x.current_position.header.stamp.secs, _x.current_position.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.current_position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.current_position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.current_position.pose.position.x, _x.current_position.pose.position.y, _x.current_position.pose.position.z, _x.current_position.pose.orientation.x, _x.current_position.pose.orientation.y, _x.current_position.pose.orientation.z, _x.current_position.pose.orientation.w, _x.current_velocity.linear.x, _x.current_velocity.linear.y, _x.current_velocity.linear.z, _x.current_velocity.angular.x, _x.current_velocity.angular.y, _x.current_velocity.angular.z,) = _get_struct_13d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_13d = None
def _get_struct_13d():
    global _struct_13d
    if _struct_13d is None:
        _struct_13d = struct.Struct("<13d")
    return _struct_13d
_struct_16B = None
def _get_struct_16B():
    global _struct_16B
    if _struct_16B is None:
        _struct_16B = struct.Struct("<16B")
    return _struct_16B
_struct_16s = None
def _get_struct_16s():
    global _struct_16s
    if _struct_16s is None:
        _struct_16s = struct.Struct("<16s")
    return _struct_16s
