local_costmap:
  global_frame: /lcr_1/odom
  robot_base_frame: /lcr_1/base_link
  update_frequency: 5.0 
  #solo per debug, poi vai a 0
  publish_frequency: 2.0
  static_map: true
  rolling_window: true
  width: 5.0
  height: 10.0
  resolution: 0.05
#per multi è 0.01
  transform_tolerance: 0.5
  plugins:
  - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
