#obstacle_range: 2.5
#raytrace_range: 2.0
# simbolo per i footprint
footprint: [[-0.3, -0.2], [-0.3, 0.2], [0.3, 0.2], [0.3, -0.2]]
#robot_radius: ir_of_robot
#inflation_radius: 0.55

#observation_sources: laser_scan_sensor #point_cloud_sensor

#laser_scan_sensor: {sensor_frame: /lcr_1/laser_link, data_type: LaserScan, topic: /lcr_1/laser_scan , marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: particlecloud, marking: true, clearing: true}

map_type: voxel

obstacle_layer:
  enabled:              true
  max_obstacle_height:  2.0
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             2
  unknown_threshold:    15
  mark_threshold:       0.1
  combination_method:   1
# track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 2.5
  raytrace_range: 3.0
  inf_is_valid: true
  publish_voxel_map: false
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    topic: /lcr_1/laser_scan
    marking: true
    clearing: true
    min_obstacle_height: 0.25
    max_obstacle_height: 2.0
    #add this
    sensor_frame: /lcr_1/laser_link
    # anche questo è aggiunto
    observation_persistence: 0.0
    #anche questo
    expected_update_rate: 0.4

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  7  # exponential rate at which the obstacle cost drops off (default: 10, was 5)
  inflation_radius:     2.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
