// Generated by gencpp from file RAN/Emergency.msg
// DO NOT EDIT!


#ifndef RAN_MESSAGE_EMERGENCY_H
#define RAN_MESSAGE_EMERGENCY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mars_common_msgs/Id.h>

namespace RAN
{
template <class ContainerAllocator>
struct Emergency_
{
  typedef Emergency_<ContainerAllocator> Type;

  Emergency_()
    : robot_id()
    , command(0)
    , description()  {
    }
  Emergency_(const ContainerAllocator& _alloc)
    : robot_id(_alloc)
    , command(0)
    , description(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mars_common_msgs::Id_<ContainerAllocator>  _robot_id_type;
  _robot_id_type robot_id;

   typedef uint8_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;



  enum {
    STOP = 0u,
    RESTART = 1u,
  };


  typedef boost::shared_ptr< ::RAN::Emergency_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RAN::Emergency_<ContainerAllocator> const> ConstPtr;

}; // struct Emergency_

typedef ::RAN::Emergency_<std::allocator<void> > Emergency;

typedef boost::shared_ptr< ::RAN::Emergency > EmergencyPtr;
typedef boost::shared_ptr< ::RAN::Emergency const> EmergencyConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RAN::Emergency_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RAN::Emergency_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RAN

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mars_agent_physical_robot_msgs': ['/home/lcr/catkin_ws/src/mars_agent_physical_robot_msg-master/msg'], 'RAN': ['/home/lcr/catkin_ws/src/RAN/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sim_msgs': ['/home/lcr/catkin_ws/src/sim_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mars_common_msgs': ['/home/lcr/catkin_ws/src/mars_common_msgs-master/msg'], 'industrial_msgs': ['/opt/ros/kinetic/share/industrial_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RAN::Emergency_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RAN::Emergency_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RAN::Emergency_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RAN::Emergency_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RAN::Emergency_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RAN::Emergency_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RAN::Emergency_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15039e86619bd710ab69714ec41122a0";
  }

  static const char* value(const ::RAN::Emergency_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15039e86619bd710ULL;
  static const uint64_t static_value2 = 0xab69714ec41122a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::RAN::Emergency_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RAN/Emergency";
  }

  static const char* value(const ::RAN::Emergency_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RAN::Emergency_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Emergency message\n\
mars_common_msgs/Id robot_id\n\
uint8 STOP = 0\n\
uint8 RESTART = 1\n\
uint8 command\n\
string description\n\
\n\
================================================================================\n\
MSG: mars_common_msgs/Id\n\
# Universally Unique Identifier (UUID)\n\
# A UUID is a 128-bit number used to identify information in computer systems. \n\
# The term globally unique identifier (GUID) is also used. \n\
# More information: https://en.wikipedia.org/wiki/Universally_unique_identifier\n\
uint8[16] uuid\n\
\n\
# optional description of the id\n\
# description can be:\n\
#   - a name\n\
#   - what is descriped by the id\n\
#   - etc.\n\
string description\n\
";
  }

  static const char* value(const ::RAN::Emergency_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RAN::Emergency_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.command);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Emergency_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RAN::Emergency_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RAN::Emergency_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    s << std::endl;
    Printer< ::mars_common_msgs::Id_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_id);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAN_MESSAGE_EMERGENCY_H
