// Generated by gencpp from file RAN/RANState.msg
// DO NOT EDIT!


#ifndef RAN_MESSAGE_RANSTATE_H
#define RAN_MESSAGE_RANSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mars_common_msgs/Id.h>
#include <RAN/RobotState.h>

namespace RAN
{
template <class ContainerAllocator>
struct RANState_
{
  typedef RANState_<ContainerAllocator> Type;

  RANState_()
    : header()
    , robot_id()
    , agv_msg()
    , ran_status(0)  {
    }
  RANState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_id(_alloc)
    , agv_msg(_alloc)
    , ran_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::mars_common_msgs::Id_<ContainerAllocator>  _robot_id_type;
  _robot_id_type robot_id;

   typedef  ::RAN::RobotState_<ContainerAllocator>  _agv_msg_type;
  _agv_msg_type agv_msg;

   typedef uint8_t _ran_status_type;
  _ran_status_type ran_status;



  enum {
    READY = 0u,
    MOVING = 1u,
    STOPPED = 2u,
  };


  typedef boost::shared_ptr< ::RAN::RANState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RAN::RANState_<ContainerAllocator> const> ConstPtr;

}; // struct RANState_

typedef ::RAN::RANState_<std::allocator<void> > RANState;

typedef boost::shared_ptr< ::RAN::RANState > RANStatePtr;
typedef boost::shared_ptr< ::RAN::RANState const> RANStateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RAN::RANState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RAN::RANState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RAN

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'mars_agent_physical_robot_msgs': ['/home/lcr/catkin_ws/src/mars_agent_physical_robot_msg-master/msg'], 'RAN': ['/home/lcr/catkin_ws/src/RAN/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sim_msgs': ['/home/lcr/catkin_ws/src/sim_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mars_common_msgs': ['/home/lcr/catkin_ws/src/mars_common_msgs-master/msg'], 'industrial_msgs': ['/opt/ros/kinetic/share/industrial_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RAN::RANState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RAN::RANState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RAN::RANState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RAN::RANState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RAN::RANState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RAN::RANState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RAN::RANState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee59b384adde6655a45d0c6d9944e17c";
  }

  static const char* value(const ::RAN::RANState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee59b384adde6655ULL;
  static const uint64_t static_value2 = 0xa45d0c6d9944e17cULL;
};

template<class ContainerAllocator>
struct DataType< ::RAN::RANState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RAN/RANState";
  }

  static const char* value(const ::RAN::RANState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RAN::RANState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message defining the Robot Agent Node status \n\
Header header\n\
mars_common_msgs/Id robot_id\n\
RobotState agv_msg\n\
# RAN status definitions\n\
uint8 READY = 0\n\
uint8 MOVING = 1\n\
uint8 STOPPED = 2\n\
uint8 ran_status # value defined as above\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: mars_common_msgs/Id\n\
# Universally Unique Identifier (UUID)\n\
# A UUID is a 128-bit number used to identify information in computer systems. \n\
# The term globally unique identifier (GUID) is also used. \n\
# More information: https://en.wikipedia.org/wiki/Universally_unique_identifier\n\
uint8[16] uuid\n\
\n\
# optional description of the id\n\
# description can be:\n\
#   - a name\n\
#   - what is descriped by the id\n\
#   - etc.\n\
string description\n\
\n\
================================================================================\n\
MSG: RAN/RobotState\n\
# Message defining the Robot / AGV status \n\
Header header\n\
mars_common_msgs/Id vehicle_id\n\
AssignmentId last_terminated_action\n\
industrial_msgs/RobotStatus robot_status\n\
sensor_msgs/BatteryState battery_state\n\
geometry_msgs/Pose2D current_position\n\
geometry_msgs/Twist current_velocity\n\
geometry_msgs/PolygonStamped footprint\n\
\n\
================================================================================\n\
MSG: RAN/AssignmentId\n\
# Message for the definition of the ids of an Assignment\n\
mars_common_msgs/Id task_id\n\
mars_common_msgs/Id action_id\n\
mars_common_msgs/Id motion_id\n\
\n\
================================================================================\n\
MSG: industrial_msgs/RobotStatus\n\
# The RobotStatus message contains low level status information \n\
# that is specific to an industrial robot controller\n\
\n\
# The header frame ID is not used\n\
Header header\n\
\n\
# The robot mode captures the operating mode of the robot.  When in\n\
# manual, remote motion is not possible.\n\
industrial_msgs/RobotMode mode\n\
\n\
# Estop status: True if robot is e-stopped.  The drives are disabled\n\
# and motion is not possible.  The e-stop condition must be acknowledged\n\
# and cleared before any motion can begin.\n\
industrial_msgs/TriState e_stopped\n\
\n\
# Drive power status: True if drives are powered.  Motion commands will \n\
# automatically enable the drives if required.  Drive power is not requred\n\
# for possible motion\n\
industrial_msgs/TriState drives_powered\n\
\n\
# Motion enabled: True if robot motion is possible.\n\
industrial_msgs/TriState motion_possible\n\
\n\
# Motion status: True if robot is in motion, otherwise false\n\
industrial_msgs/TriState in_motion\n\
\n\
# Error status: True if there is an error condition on the robot. Motion may\n\
# or may not be affected (see motion_possible)\n\
industrial_msgs/TriState in_error\n\
\n\
# Error code: Vendor specific error code (non zero indicates error)\n\
int32 error_code\n\
\n\
================================================================================\n\
MSG: industrial_msgs/RobotMode\n\
# The Robot mode message encapsulates the mode/teach state of the robot\n\
# Typically this is controlled by the pendant key switch, but not always\n\
\n\
int8 val\n\
\n\
# enumerated values\n\
int8 UNKNOWN=-1                 # Unknown or unavailable         \n\
int8 MANUAL=1 			 # Teach OR manual mode\n\
int8 AUTO=2                     # Automatic mode\n\
\n\
\n\
================================================================================\n\
MSG: industrial_msgs/TriState\n\
# The tri-state captures boolean values with the additional state of unknown\n\
\n\
int8 val\n\
\n\
# enumerated values\n\
\n\
# Unknown or unavailable \n\
int8 UNKNOWN=-1  \n\
\n\
# High state                       \n\
int8 TRUE=1\n\
int8 ON=1\n\
int8 ENABLED=1\n\
int8 HIGH=1\n\
int8 CLOSED=1\n\
\n\
# Low state\n\
int8 FALSE=0\n\
int8 OFF=0\n\
int8 DISABLED=0\n\
int8 LOW=0\n\
int8 OPEN=0\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/BatteryState\n\
\n\
# Constants are chosen to match the enums in the linux kernel\n\
# defined in include/linux/power_supply.h as of version 3.7\n\
# The one difference is for style reasons the constants are\n\
# all uppercase not mixed case.\n\
\n\
# Power supply status constants\n\
uint8 POWER_SUPPLY_STATUS_UNKNOWN = 0\n\
uint8 POWER_SUPPLY_STATUS_CHARGING = 1\n\
uint8 POWER_SUPPLY_STATUS_DISCHARGING = 2\n\
uint8 POWER_SUPPLY_STATUS_NOT_CHARGING = 3\n\
uint8 POWER_SUPPLY_STATUS_FULL = 4\n\
\n\
# Power supply health constants\n\
uint8 POWER_SUPPLY_HEALTH_UNKNOWN = 0\n\
uint8 POWER_SUPPLY_HEALTH_GOOD = 1\n\
uint8 POWER_SUPPLY_HEALTH_OVERHEAT = 2\n\
uint8 POWER_SUPPLY_HEALTH_DEAD = 3\n\
uint8 POWER_SUPPLY_HEALTH_OVERVOLTAGE = 4\n\
uint8 POWER_SUPPLY_HEALTH_UNSPEC_FAILURE = 5\n\
uint8 POWER_SUPPLY_HEALTH_COLD = 6\n\
uint8 POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE = 7\n\
uint8 POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE = 8\n\
\n\
# Power supply technology (chemistry) constants\n\
uint8 POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 0\n\
uint8 POWER_SUPPLY_TECHNOLOGY_NIMH = 1\n\
uint8 POWER_SUPPLY_TECHNOLOGY_LION = 2\n\
uint8 POWER_SUPPLY_TECHNOLOGY_LIPO = 3\n\
uint8 POWER_SUPPLY_TECHNOLOGY_LIFE = 4\n\
uint8 POWER_SUPPLY_TECHNOLOGY_NICD = 5\n\
uint8 POWER_SUPPLY_TECHNOLOGY_LIMN = 6\n\
\n\
Header  header\n\
float32 voltage          # Voltage in Volts (Mandatory)\n\
float32 current          # Negative when discharging (A)  (If unmeasured NaN)\n\
float32 charge           # Current charge in Ah  (If unmeasured NaN)\n\
float32 capacity         # Capacity in Ah (last full capacity)  (If unmeasured NaN)\n\
float32 design_capacity  # Capacity in Ah (design capacity)  (If unmeasured NaN)\n\
float32 percentage       # Charge percentage on 0 to 1 range  (If unmeasured NaN)\n\
uint8   power_supply_status     # The charging status as reported. Values defined above\n\
uint8   power_supply_health     # The battery health metric. Values defined above\n\
uint8   power_supply_technology # The battery chemistry. Values defined above\n\
bool    present          # True if the battery is present\n\
\n\
float32[] cell_voltage   # An array of individual cell voltages for each cell in the pack\n\
                         # If individual voltages unknown but number of cells known set each to NaN\n\
string location          # The location into which the battery is inserted. (slot number or plug)\n\
string serial_number     # The best approximation of the battery serial number\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/PolygonStamped\n\
# This represents a Polygon with reference coordinate frame and timestamp\n\
Header header\n\
Polygon polygon\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Polygon\n\
#A specification of a polygon where the first and last points are assumed to be connected\n\
Point32[] points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::RAN::RANState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RAN::RANState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_id);
      stream.next(m.agv_msg);
      stream.next(m.ran_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RANState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RAN::RANState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RAN::RANState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_id: ";
    s << std::endl;
    Printer< ::mars_common_msgs::Id_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_id);
    s << indent << "agv_msg: ";
    s << std::endl;
    Printer< ::RAN::RobotState_<ContainerAllocator> >::stream(s, indent + "  ", v.agv_msg);
    s << indent << "ran_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ran_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAN_MESSAGE_RANSTATE_H
