(cl:in-package opil_v2-msg)
(cl:export '(HEADER-VAL
          HEADER
          VEHICLE_ID-VAL
          VEHICLE_ID
          LEFT_SIZE-VAL
          LEFT_SIZE
          RIGHT_SIZE-VAL
          RIGHT_SIZE
          FRONT_SIZE-VAL
          FRONT_SIZE
          REAR_SIZE-VAL
          REAR_SIZE
          MIN_HEIGHT-VAL
          MIN_HEIGHT
          MAX_HEIGHT-VAL
          MAX_HEIGHT
          PAYLOAD-VAL
          PAYLOAD
          MAX_POS_X_VEL-VAL
          MAX_POS_X_VEL
          MAX_NEG_X_VEL-VAL
          MAX_NEG_X_VEL
          MAX_POS_X_ACC-VAL
          MAX_POS_X_ACC
          MAX_NEG_X_ACC-VAL
          MAX_NEG_X_ACC
          MAX_POS_Y_VEL-VAL
          MAX_POS_Y_VEL
          MAX_NEG_Y_VEL-VAL
          MAX_NEG_Y_VEL
          MAX_POS_Y_ACC-VAL
          MAX_POS_Y_ACC
          MAX_NEG_Y_ACC-VAL
          MAX_NEG_Y_ACC
          MAX_POS_ANG_VEL-VAL
          MAX_POS_ANG_VEL
          MAX_NEG_ANG_VEL-VAL
          MAX_NEG_ANG_VEL
          VELOCITY_CONTROL_SENSITIVITY-VAL
          VELOCITY_CONTROL_SENSITIVITY
          MIN_TURNING_RADIUS-VAL
          MIN_TURNING_RADIUS
          BATT_CAPACITY-VAL
          BATT_CAPACITY
          BATT_MAX_VOLTAGE-VAL
          BATT_MAX_VOLTAGE
          VEHICLE_TYPE-VAL
          VEHICLE_TYPE
          VENDOR-VAL
          VENDOR
          ACTION_CAPABILITY-VAL
          ACTION_CAPABILITY
))