// Generated by gencpp from file lcr_shared/SetPose.msg
// DO NOT EDIT!


#ifndef LCR_SHARED_MESSAGE_SETPOSE_H
#define LCR_SHARED_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <lcr_shared/SetPoseRequest.h>
#include <lcr_shared/SetPoseResponse.h>


namespace lcr_shared
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace lcr_shared


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lcr_shared::SetPose > {
  static const char* value()
  {
    return "b66f4c8c2fa81b98544cf0f3e10950ee";
  }

  static const char* value(const ::lcr_shared::SetPose&) { return value(); }
};

template<>
struct DataType< ::lcr_shared::SetPose > {
  static const char* value()
  {
    return "lcr_shared/SetPose";
  }

  static const char* value(const ::lcr_shared::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::lcr_shared::SetPoseRequest> should match 
// service_traits::MD5Sum< ::lcr_shared::SetPose > 
template<>
struct MD5Sum< ::lcr_shared::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lcr_shared::SetPose >::value();
  }
  static const char* value(const ::lcr_shared::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lcr_shared::SetPoseRequest> should match 
// service_traits::DataType< ::lcr_shared::SetPose > 
template<>
struct DataType< ::lcr_shared::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::lcr_shared::SetPose >::value();
  }
  static const char* value(const ::lcr_shared::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lcr_shared::SetPoseResponse> should match 
// service_traits::MD5Sum< ::lcr_shared::SetPose > 
template<>
struct MD5Sum< ::lcr_shared::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lcr_shared::SetPose >::value();
  }
  static const char* value(const ::lcr_shared::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lcr_shared::SetPoseResponse> should match 
// service_traits::DataType< ::lcr_shared::SetPose > 
template<>
struct DataType< ::lcr_shared::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::lcr_shared::SetPose >::value();
  }
  static const char* value(const ::lcr_shared::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LCR_SHARED_MESSAGE_SETPOSE_H
