// Generated by gencpp from file lcr_shared/wcs_status.msg
// DO NOT EDIT!


#ifndef LCR_SHARED_MESSAGE_WCS_STATUS_H
#define LCR_SHARED_MESSAGE_WCS_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>

namespace lcr_shared
{
template <class ContainerAllocator>
struct wcs_status_
{
  typedef wcs_status_<ContainerAllocator> Type;

  wcs_status_()
    : virtual_object_version_id(0)
    , mission_id()
    , wcs_adapter_ros_header()
    , status(0)
    , error_type(0)
    , error_id()
    , error_header()  {
    }
  wcs_status_(const ContainerAllocator& _alloc)
    : virtual_object_version_id(0)
    , mission_id(_alloc)
    , wcs_adapter_ros_header(_alloc)
    , status(0)
    , error_type(0)
    , error_id(_alloc)
    , error_header(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _virtual_object_version_id_type;
  _virtual_object_version_id_type virtual_object_version_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mission_id_type;
  _mission_id_type mission_id;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _wcs_adapter_ros_header_type;
  _wcs_adapter_ros_header_type wcs_adapter_ros_header;

   typedef int8_t _status_type;
  _status_type status;

   typedef int8_t _error_type_type;
  _error_type_type error_type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_id_type;
  _error_id_type error_id;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _error_header_type;
  _error_header_type error_header;





  typedef boost::shared_ptr< ::lcr_shared::wcs_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lcr_shared::wcs_status_<ContainerAllocator> const> ConstPtr;

}; // struct wcs_status_

typedef ::lcr_shared::wcs_status_<std::allocator<void> > wcs_status;

typedef boost::shared_ptr< ::lcr_shared::wcs_status > wcs_statusPtr;
typedef boost::shared_ptr< ::lcr_shared::wcs_status const> wcs_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lcr_shared::wcs_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lcr_shared::wcs_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lcr_shared

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'lcr_shared': ['/home/lcr/catkin_ws/src/lcr_shared/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lcr_shared::wcs_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lcr_shared::wcs_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcr_shared::wcs_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcr_shared::wcs_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcr_shared::wcs_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcr_shared::wcs_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lcr_shared::wcs_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe2a2cc15ab59605464b4b1259d9135";
  }

  static const char* value(const ::lcr_shared::wcs_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe2a2cc15ab5960ULL;
  static const uint64_t static_value2 = 0x5464b4b1259d9135ULL;
};

template<class ContainerAllocator>
struct DataType< ::lcr_shared::wcs_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lcr_shared/wcs_status";
  }

  static const char* value(const ::lcr_shared::wcs_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lcr_shared::wcs_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 virtual_object_version_id\n\
string mission_id\n\
Header wcs_adapter_ros_header\n\
int8 status\n\
int8 error_type #0 no error\n\
string error_id\n\
Header error_header\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::lcr_shared::wcs_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lcr_shared::wcs_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.virtual_object_version_id);
      stream.next(m.mission_id);
      stream.next(m.wcs_adapter_ros_header);
      stream.next(m.status);
      stream.next(m.error_type);
      stream.next(m.error_id);
      stream.next(m.error_header);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wcs_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lcr_shared::wcs_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lcr_shared::wcs_status_<ContainerAllocator>& v)
  {
    s << indent << "virtual_object_version_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.virtual_object_version_id);
    s << indent << "mission_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mission_id);
    s << indent << "wcs_adapter_ros_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.wcs_adapter_ros_header);
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
    s << indent << "error_type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.error_type);
    s << indent << "error_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_id);
    s << indent << "error_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.error_header);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LCR_SHARED_MESSAGE_WCS_STATUS_H
