// Generated by gencpp from file mars_agent_physical_robot_msgs/ActualState.msg
// DO NOT EDIT!


#ifndef MARS_AGENT_PHYSICAL_ROBOT_MSGS_MESSAGE_ACTUALSTATE_H
#define MARS_AGENT_PHYSICAL_ROBOT_MSGS_MESSAGE_ACTUALSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mars_common_msgs/Id.h>

namespace mars_agent_physical_robot_msgs
{
template <class ContainerAllocator>
struct ActualState_
{
  typedef ActualState_<ContainerAllocator> Type;

  ActualState_()
    : header()
    , robot_id()
    , MoveBaseSimpleState(0)  {
    }
  ActualState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_id(_alloc)
    , MoveBaseSimpleState(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::mars_common_msgs::Id_<ContainerAllocator>  _robot_id_type;
  _robot_id_type robot_id;

   typedef uint8_t _MoveBaseSimpleState_type;
  _MoveBaseSimpleState_type MoveBaseSimpleState;



  enum {
    MBS_NO_POSITION = 0u,
    MBS_WAITING_FOR_INIT = 1u,
    MBS_READY = 2u,
    MBS_FIRST_ROTATION = 3u,
    MBS_MOVING = 4u,
    MBS_SECOND_ROTATION = 5u,
    MBS_FINISHED = 6u,
    MBS_FETCH_NEXT_INSTRUCTION = 7u,
    MBS_EXECUTE_ACTION = 8u,
    MBS_OBSTACLE = 9u,
    MBS_ERROR = 10u,
  };


  typedef boost::shared_ptr< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> const> ConstPtr;

}; // struct ActualState_

typedef ::mars_agent_physical_robot_msgs::ActualState_<std::allocator<void> > ActualState;

typedef boost::shared_ptr< ::mars_agent_physical_robot_msgs::ActualState > ActualStatePtr;
typedef boost::shared_ptr< ::mars_agent_physical_robot_msgs::ActualState const> ActualStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mars_agent_physical_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'mars_agent_physical_robot_msgs': ['/home/lcr/catkin_ws/src/mars_agent_physical_robot_msg-master/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mars_common_msgs': ['/home/lcr/catkin_ws/src/mars_common_msgs-master/msg'], 'industrial_msgs': ['/opt/ros/kinetic/share/industrial_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "218dfb6147c7753072d56e5c9678828c";
  }

  static const char* value(const ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x218dfb6147c77530ULL;
  static const uint64_t static_value2 = 0x72d56e5c9678828cULL;
};

template<class ContainerAllocator>
struct DataType< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mars_agent_physical_robot_msgs/ActualState";
  }

  static const char* value(const ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message for the Actual State\n\
std_msgs/Header header\n\
mars_common_msgs/Id robot_id\n\
# Definition of all possible States\n\
uint8 MBS_NO_POSITION = 0\n\
uint8 MBS_WAITING_FOR_INIT = 1\n\
uint8 MBS_READY = 2\n\
uint8 MBS_FIRST_ROTATION = 3\n\
uint8 MBS_MOVING = 4\n\
uint8 MBS_SECOND_ROTATION = 5\n\
uint8 MBS_FINISHED = 6\n\
uint8 MBS_FETCH_NEXT_INSTRUCTION = 7\n\
uint8 MBS_EXECUTE_ACTION = 8\n\
uint8 MBS_OBSTACLE = 9\n\
uint8 MBS_ERROR = 10\n\
uint8 MoveBaseSimpleState\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: mars_common_msgs/Id\n\
# Universally Unique Identifier (UUID)\n\
# A UUID is a 128-bit number used to identify information in computer systems. \n\
# The term globally unique identifier (GUID) is also used. \n\
# More information: https://en.wikipedia.org/wiki/Universally_unique_identifier\n\
uint8[16] uuid\n\
\n\
# optional description of the id\n\
# description can be:\n\
#   - a name\n\
#   - what is descriped by the id\n\
#   - etc.\n\
string description\n\
";
  }

  static const char* value(const ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_id);
      stream.next(m.MoveBaseSimpleState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActualState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mars_agent_physical_robot_msgs::ActualState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_id: ";
    s << std::endl;
    Printer< ::mars_common_msgs::Id_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_id);
    s << indent << "MoveBaseSimpleState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.MoveBaseSimpleState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARS_AGENT_PHYSICAL_ROBOT_MSGS_MESSAGE_ACTUALSTATE_H
