// Generated by gencpp from file mars_agent_physical_robot_msgs/AssignmentStatus.msg
// DO NOT EDIT!


#ifndef MARS_AGENT_PHYSICAL_ROBOT_MSGS_MESSAGE_ASSIGNMENTSTATUS_H
#define MARS_AGENT_PHYSICAL_ROBOT_MSGS_MESSAGE_ASSIGNMENTSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mars_common_msgs/Id.h>
#include <mars_common_msgs/Id.h>
#include <mars_common_msgs/Id.h>
#include <mars_common_msgs/Id.h>
#include <mars_common_msgs/Id.h>
#include <geometry_msgs/PolygonStamped.h>

namespace mars_agent_physical_robot_msgs
{
template <class ContainerAllocator>
struct AssignmentStatus_
{
  typedef AssignmentStatus_<ContainerAllocator> Type;

  AssignmentStatus_()
    : current_task_id()
    , current_motion_id()
    , current_action_id()
    , last_finished_motion()
    , last_finished_action()
    , footprint()  {
    }
  AssignmentStatus_(const ContainerAllocator& _alloc)
    : current_task_id(_alloc)
    , current_motion_id(_alloc)
    , current_action_id(_alloc)
    , last_finished_motion(_alloc)
    , last_finished_action(_alloc)
    , footprint(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mars_common_msgs::Id_<ContainerAllocator>  _current_task_id_type;
  _current_task_id_type current_task_id;

   typedef  ::mars_common_msgs::Id_<ContainerAllocator>  _current_motion_id_type;
  _current_motion_id_type current_motion_id;

   typedef  ::mars_common_msgs::Id_<ContainerAllocator>  _current_action_id_type;
  _current_action_id_type current_action_id;

   typedef  ::mars_common_msgs::Id_<ContainerAllocator>  _last_finished_motion_type;
  _last_finished_motion_type last_finished_motion;

   typedef  ::mars_common_msgs::Id_<ContainerAllocator>  _last_finished_action_type;
  _last_finished_action_type last_finished_action;

   typedef  ::geometry_msgs::PolygonStamped_<ContainerAllocator>  _footprint_type;
  _footprint_type footprint;





  typedef boost::shared_ptr< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> const> ConstPtr;

}; // struct AssignmentStatus_

typedef ::mars_agent_physical_robot_msgs::AssignmentStatus_<std::allocator<void> > AssignmentStatus;

typedef boost::shared_ptr< ::mars_agent_physical_robot_msgs::AssignmentStatus > AssignmentStatusPtr;
typedef boost::shared_ptr< ::mars_agent_physical_robot_msgs::AssignmentStatus const> AssignmentStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mars_agent_physical_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mars_agent_physical_robot_msgs': ['/home/lcr/catkin_ws/src/mars_agent_physical_robot_msg-master/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mars_common_msgs': ['/home/lcr/catkin_ws/src/mars_common_msgs-master/msg'], 'industrial_msgs': ['/opt/ros/kinetic/share/industrial_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51331f0d54af7e13d2a0c817444fec5e";
  }

  static const char* value(const ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51331f0d54af7e13ULL;
  static const uint64_t static_value2 = 0xd2a0c817444fec5eULL;
};

template<class ContainerAllocator>
struct DataType< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mars_agent_physical_robot_msgs/AssignmentStatus";
  }

  static const char* value(const ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mars_common_msgs/Id current_task_id\n\
mars_common_msgs/Id current_motion_id\n\
mars_common_msgs/Id current_action_id\n\
mars_common_msgs/Id last_finished_motion\n\
mars_common_msgs/Id last_finished_action\n\
geometry_msgs/PolygonStamped footprint\n\
\n\
================================================================================\n\
MSG: mars_common_msgs/Id\n\
# Universally Unique Identifier (UUID)\n\
# A UUID is a 128-bit number used to identify information in computer systems. \n\
# The term globally unique identifier (GUID) is also used. \n\
# More information: https://en.wikipedia.org/wiki/Universally_unique_identifier\n\
uint8[16] uuid\n\
\n\
# optional description of the id\n\
# description can be:\n\
#   - a name\n\
#   - what is descriped by the id\n\
#   - etc.\n\
string description\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PolygonStamped\n\
# This represents a Polygon with reference coordinate frame and timestamp\n\
Header header\n\
Polygon polygon\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Polygon\n\
#A specification of a polygon where the first and last points are assumed to be connected\n\
Point32[] points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_task_id);
      stream.next(m.current_motion_id);
      stream.next(m.current_action_id);
      stream.next(m.last_finished_motion);
      stream.next(m.last_finished_action);
      stream.next(m.footprint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AssignmentStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mars_agent_physical_robot_msgs::AssignmentStatus_<ContainerAllocator>& v)
  {
    s << indent << "current_task_id: ";
    s << std::endl;
    Printer< ::mars_common_msgs::Id_<ContainerAllocator> >::stream(s, indent + "  ", v.current_task_id);
    s << indent << "current_motion_id: ";
    s << std::endl;
    Printer< ::mars_common_msgs::Id_<ContainerAllocator> >::stream(s, indent + "  ", v.current_motion_id);
    s << indent << "current_action_id: ";
    s << std::endl;
    Printer< ::mars_common_msgs::Id_<ContainerAllocator> >::stream(s, indent + "  ", v.current_action_id);
    s << indent << "last_finished_motion: ";
    s << std::endl;
    Printer< ::mars_common_msgs::Id_<ContainerAllocator> >::stream(s, indent + "  ", v.last_finished_motion);
    s << indent << "last_finished_action: ";
    s << std::endl;
    Printer< ::mars_common_msgs::Id_<ContainerAllocator> >::stream(s, indent + "  ", v.last_finished_action);
    s << indent << "footprint: ";
    s << std::endl;
    Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.footprint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARS_AGENT_PHYSICAL_ROBOT_MSGS_MESSAGE_ASSIGNMENTSTATUS_H
