// Generated by gencpp from file opil_v2/ErrorAGV.msg
// DO NOT EDIT!


#ifndef OPIL_V2_MESSAGE_ERRORAGV_H
#define OPIL_V2_MESSAGE_ERRORAGV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <opil_v2/Id.h>

namespace opil_v2
{
template <class ContainerAllocator>
struct ErrorAGV_
{
  typedef ErrorAGV_<ContainerAllocator> Type;

  ErrorAGV_()
    : header()
    , vehicle_id()
    , error_AGV(0)
    , description()  {
    }
  ErrorAGV_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehicle_id(_alloc)
    , error_AGV(0)
    , description(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::opil_v2::Id_<ContainerAllocator>  _vehicle_id_type;
  _vehicle_id_type vehicle_id;

   typedef uint8_t _error_AGV_type;
  _error_AGV_type error_AGV;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;





  typedef boost::shared_ptr< ::opil_v2::ErrorAGV_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opil_v2::ErrorAGV_<ContainerAllocator> const> ConstPtr;

}; // struct ErrorAGV_

typedef ::opil_v2::ErrorAGV_<std::allocator<void> > ErrorAGV;

typedef boost::shared_ptr< ::opil_v2::ErrorAGV > ErrorAGVPtr;
typedef boost::shared_ptr< ::opil_v2::ErrorAGV const> ErrorAGVConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opil_v2::ErrorAGV_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opil_v2::ErrorAGV_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opil_v2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'opil_v2': ['/home/lcr/catkin_ws/src/OLD_opil_v2/msg'], 'industrial_msgs': ['/opt/ros/kinetic/share/industrial_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opil_v2::ErrorAGV_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opil_v2::ErrorAGV_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opil_v2::ErrorAGV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opil_v2::ErrorAGV_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opil_v2::ErrorAGV_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opil_v2::ErrorAGV_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opil_v2::ErrorAGV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78ad4f48718cf35af4c2e5acf0a34b81";
  }

  static const char* value(const ::opil_v2::ErrorAGV_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78ad4f48718cf35aULL;
  static const uint64_t static_value2 = 0xf4c2e5acf0a34b81ULL;
};

template<class ContainerAllocator>
struct DataType< ::opil_v2::ErrorAGV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opil_v2/ErrorAGV";
  }

  static const char* value(const ::opil_v2::ErrorAGV_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opil_v2::ErrorAGV_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Error message from the AGV\n\
std_msgs/Header header\n\
Id vehicle_id\n\
uint8 error_AGV\n\
string description\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: opil_v2/Id\n\
# Message for defining IDs\n\
# numeric ID\n\
uint32 id\n\
\n\
# optional description of the id\n\
# description can be:\n\
#   - a name\n\
#   - what is descriped by the id\n\
#   - etc.\n\
\n\
string description\n\
\n\
";
  }

  static const char* value(const ::opil_v2::ErrorAGV_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opil_v2::ErrorAGV_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehicle_id);
      stream.next(m.error_AGV);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ErrorAGV_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opil_v2::ErrorAGV_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opil_v2::ErrorAGV_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehicle_id: ";
    s << std::endl;
    Printer< ::opil_v2::Id_<ContainerAllocator> >::stream(s, indent + "  ", v.vehicle_id);
    s << indent << "error_AGV: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_AGV);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPIL_V2_MESSAGE_ERRORAGV_H
