(cl:defpackage RAN-msg
  (:use )
  (:export
   "<ACTIONDEFINITION>"
   "ACTIONDEFINITION"
   "<ASSIGNMENTID>"
   "ASSIGNMENTID"
   "<ELEVATORSTATUS>"
   "ELEVATORSTATUS"
   "<EMERGENCY>"
   "EMERGENCY"
   "<ERRORAGV>"
   "ERRORAGV"
   "<RANSTATE>"
   "RANSTATE"
   "<ROBOTDESCRIPTIONAGV>"
   "ROBOTDESCRIPTIONAGV"
   "<ROBOTSTATE>"
   "ROBOTSTATE"
  ))

